### ISSUE TITLE
Private, protected and public modes

### ISSUE THREAD

**Issue by namansamra** [RocketMeet/RocketMeet-client#102]
I came up an issue that when a poll is created and shared .
A user(without even login) can give his/her selection any number of times with fake names. This might be a cautious security issue because any user can give many opinion on the poll which can even ruin the purpose of poll.

Please correct me if I am wrong. @AnandBaburajan

**Comment by anaswaratrajan** [comment]
Hi @namansamra ! It was intentional. The poll page is accessible by the public and anyone can poll anonymously (just like normal polls). Besides, the poll author can pick the feasible time for himself from the other votes if ignore the anonymous votes from fake names. I see no security issue here. But, thanks for bringing your worry to us! :D

PS. The only issue I see here is if someone voted as an imposter. Polling with the name of some other invitee. @AnandBaburajan what do you think?

**Comment by AnandBaburajan** [comment]
We let people vote without logging in to make it quick for them and we went with this decision because Doodle does it the same way. Though I think this approach is fine if the voters are trustworthy, the downsides mentioned here are indeed worth looking into. I think we should discuss this at our Gitter chatroom and let everyone chime in! Thanks for bringing this up!

**Comment by namansamra** [comment]
@AnandBaburajan                                                                                                                                                    
So as per gitter discussion on this issue a possible solution would be :
There will me three modes for creating pole:

1.Public mode: 
-Any user with that link can share his opinion on the pole.
-It works well when we have a guest user or the intention of the poll is to get the opinion of mass users.

2.Protected mode:
-A user must be logged in to vote on the poll.
-A user can vote only one time with that google account.
-It will work well to avoid any imposter/ fake user to intrigue in the poll.

3. Private mode
-A user could only vote in this type of poll if he/she has received the invitation through mail.
-It will work well if the creator of the poll wants only specific people to vote on the poll.

**Comment by BreadGenie** [comment]
Will there be share invite link option with private mode or just send mail option?

**Comment by AnandBaburajan** [comment]
> Will there be share invite link option with private mode or just send mail option?

Maybe neither of those - we could have a box on the create poll page itself (under the private option) to enter the email IDs?

**Comment by AnandBaburajan** [comment]
Public and protected modes were added with #135. I've opened #136 for private mode.
