### ISSUE TITLE
Shell script to run all the development servers locally

### ISSUE THREAD

**Issue by anaswaratrajan** [RocketMeet/RocketMeet-client#65]
**Have to manually run the 3 different servers and `mongod` at once**
- For `development`, developer needs to setup and start [RocketMeet-server](https://github.com/RocketMeet/RocketMeet-server), [RocketMeet-mailer](https://github.com/RocketMeet/RocketMeet-mailer) and a `mongod` connection before starting Rocketmeet-client development server with `npm run dev`

**Solution: shell script to start all 4 servers**
- Write a shell script to start all the 4 development servers at once. Possibly from project root.

**Comment by viveknathani** [comment]
Hello. Can you assign this issue to me? I have written shell scripts in the past. If I understand it correctly, the order of execution of starting servers should be, 
1. starting the mongod service
2. starting the RocketMeet-server
3. starting the RocketMeet-mailer
4. starting the RocketMeet-client

**Comment by BreadGenie** [comment]
In my opinion 1st option is better than 2nd since developers would rather clone repositories in the same directory than fill out the path in the script
also we can put that in the setup instructions if we go by option 1
@AnandBaburajan @anaswaratrajan  what do you guys think?

**Comment by anaswaratrajan** [comment]
Yep, you can go with option 1, but I recommend writing another script with option 2 for those who might have placed the repositories in different directories. 

Also, how do you plan on starting multiple servers from the same script?

**Comment by viveknathani** [comment]
Instead of writing another script, could I allow two command line arguments to be processed?
$1 for RocketMeet-server's path.
$2 for RocketMeet-mailer's path.

The idea is to run the relevant commands using '&'.  
Example:
```bash
command1 & command2 & command3
```
The problem here is the order of execution becomes nondeterministic as running the process goes into the hands of the CPU scheduler.

The workaround I could think for this is to prompt the user to enter something, let's say "mailer" after seeing the success of RocketMeet-server being started. Once the "mailer" string is entered, the script proceeds further to start mailer. Similar steps are carried out for starting the client only after the mailer has started. 

Example:
```bash
command1 &
read input
command2 &
read input
command3
```
In this way, the CPU has no choice but to wait for the input before starting another server.

**Comment by AnandBaburajan** [comment]
Just curious, do we really need to run the services in a particular order? The server can wait for mongod to start and then make the connection, right? So can't they all be started in parallel? Please explore and let us know if that's not a recommended practice. On a related note, @PushkarDureja is looking into using Docker Compose for RocketMeet too.

**Comment by viveknathani** [comment]
@AnandBaburajan yes you are right about the order part. I could not find anything about parallel running not being a recommended practice. So I guess I could proceed without preserving the order? Also, I am not aware about usage of Docker so I cannot understand what you mean to imply in the end.

**Comment by AnandBaburajan** [comment]
> I could not find anything about parallel running not being a recommended practice

Thanks for looking into it!

> So I guess I could proceed without preserving the order?

Yep, and let us know if there are any issues.

> Also, I am not aware about usage of Docker so I cannot understand what you mean to imply in the end.

Docker Compose is used to run multiple containers as a single service so users would have the option to use that to run RM.
You don't need to worry about it now. Just a different way to solve the same issue.

**Comment by viveknathani** [comment]
All right. I made the PR.
